### ISSUE TITLE
segfault due to GTK2 upgrade Arch Linux

### ISSUE THREAD

**Issue by ryanvade** [spotify/linux#1]
Receiving a segfault on Arch Linux with GTK2 2..24.26-1. Downgrading to 2.24.25-1 still works:
https://aur.archlinux.org/packages/spotify/

**Comment by rpp0** [comment]
Same here. Happens after playing a song for about 30 seconds.

**Comment by ryanvade** [comment]
I just noticed that this is for the spotify linux kernel.  My apolobies for opening this here.

**Comment by ArthurGarnier** [comment]
Same after playing few seconds, and on "Starred" playlist display

**Comment by lucianomagrao** [comment]
Same here, Feroda 21. Downgrading gtk2 still works.

**Comment by djmaze** [comment]
@leslau: It is fixed with gtk2 2.24.27-1. See at https://aur.archlinux.org/packages/spotify/.

**Comment by lucianomagrao** [comment]
@djmaze thks

Already pushed to stable https://admin.fedoraproject.org/updates/gtk2-2.24.27-1.fc21
